window.INVITATION_DATA = {
  groomFirst: "Depon",
  groomFull: "Daffa Imam Praditya, S.S",
  groomParents: "Bapak Ikhwan Ruswandi & Ibu Memes",
  brideFirst: "Osyah",
  brideFull: "Rossa Sahara, S.Kom",
  brideParents: "Bapak Rochmat (Tom-tom) & Ibu Vivi Fitriati",
  eventDateISO: "2026-10-25T10:00:00+07:00",
  eventDateLong: "Minggu, 25 Oktober 2026",
  eventDateShort: "25 · 10 · 2026",
  eventDay: "25",
  eventDayName: "Minggu",
  eventMonthYear: "Oktober 2026",
  eventTime: "10.00 WIB–selesai",
  venueName: "Kediaman Keluarga",
  venueAddress: "Jl. Sektor 15D RT 05/RW 010, Sudimara Jaya, Ciledug",
  mapsUrl: "https://www.google.com/maps/search/?api=1&query=Jl.+Sektor+15D+RT+05%2FRW+010%2C+Sudimara+Jaya%2C+Ciledug",
};
